runtime: go112

handlers:
- url: /anal.js
  static_files: anal.js
  upload: anal.js
  secure: always
  # default_headers Cache-Control X-Frame-Options Content-Security-Policy

- url: /analsandbox/.*
  static_files: anal.html
  upload: anal.html
  secure: always
  # default_headers Cache-Control X-Frame-Options Content-Security-Policy

- url: /chat-widget.js
  static_files: chat-widget.js
  upload: chat-widget.js
  secure: always
  # default_headers Cache-Control X-Frame-Options Content-Security-Policy

- url: .*
  script: auto
  secure: always
